services:

  # 0. DBs
  db:
    image: postgres:16.1
    container_name: explore-with-me-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d   # пробросить путь на хосте (./initdb): в фиксированную директорию внутри контейнера, которую официальный образ PostgreSQL автоматически обрабатывает при первом запуске
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network
    profiles: [ "main" ]

  # 1. Discovery Server (Eureka)
  discovery-server:
    image: discovery-server:latest        # имя образа, который будет создан или использован. Если есть build, образ собирается локально, а не скачивается из Docker Hub. C тегом :latest
    build:
      context: ./infra/discovery-server   # где искать исходники: в пакете ./infra/discovery-server
      dockerfile: Dockerfile              # как собирать образ: используя файл Dockerfile, в этой папке
    ports:
      - "8761:8761"                       # пробросить порт (порт на компьютере (localhost):порт внутри контейнера)
    depends_on:
      db:
        condition: service_healthy
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s                       # проверять каждые 10 секунд
      timeout: 5s                         # ждать ответа не дольше 5 секунд
      retries: 3                          # сделать до 3 попыток, прежде чем считать сервис "нездоровым"
    restart: unless-stopped               # перезапускать, если контейнер не был остановлен вручную
    networks:
      - app-network                       # контейнер должен быть подключен к с именем app-network
    profiles: [ "main" ]                  # запуск по профилю 'docker compose --profile main up -d'

  # 2. Config Server
  config-server:
    image: config-server:latest
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles: [ "main" ]

  # 3. Main Service
  main-service:
    image: main-service:latest
    deploy:
      restart_policy:
        condition: on-failure             # перезапускать контейнер только если он завершился с ненулевым кодом (упал с ошибкой)
        delay: 5s                         # ждать 5 секунд перед попыткой перезапуска
        max_attempts: 3                   # максимум 3 попытки перезапуска
        window: 120s                      # временное окно, в течение которого считаются попытки. Если за 120 секунд было 3 падения, Docker перестанет пытаться перезапускать контейнер
    build:
      context: ./core/main-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"                       # порт для дебага
    depends_on:
      db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:                          # переменные окружения внутри контейнера
                                          # > - все строки ниже объединить в одну строку с пробелами вместо переносов
                                          # -agentlib:jdwp - настройка удалённой отладки Java (JDWP - Java Debug Wire Protocol).
                                          # Позволяет подключить IDE к работающему контейнеру и ставить breakpoints, как будто
                                          # приложение запущено локально.
                                          # -Duser.timezone - устанавливает часовой пояс по умолчанию для всего приложения
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles: [ "main" ]

  # 4. Stats Server
  stats-server:
    image: stats-server:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    ports:
      - "5006:5005"                       # порт для дебага
    depends_on:
      db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles: [ "main" ]

  # 5. Gateway Server
  gateway-server:
    image: gateway-server:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles: [ "main" ]

networks:
  app-network:
    driver: bridge                        # объявляет внутреннюю сеть, чтобы контейнеры могли общяться между собой по имени сервиса (как по hostname) н.п. http://db:5432
