services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"                       # Внешний доступ для клиентов с хоста
      - "9101:9101"                       # JMX-мониторинг
    restart: unless-stopped
    environment:
      # Идентификаторы
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "K0EA9p0yEe6MkAAAAkKsEg"

      # Роли Kafka (для KRaft mode)
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # Слушатели: внутренние и внешние
      KAFKA_LISTENERS: >-                 # >- склеивает всё в одну строку без переносов, но сохраняет запятые и пробелы
        PLAINTEXT://kafka:29092,
        CONTROLLER://kafka:29093,
        PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: >-
        PLAINTEXT://kafka:29092,
        PLAINTEXT_HOST://localhost:9092

      # JMX
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    profiles:
      - default
      - docker

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: >-
      bash -c "
        kafka-topics --create --topic stats.user-actions.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic stats.events-similarity.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092
      "
    init: true
    profiles:
      - default
      - docker

  # 0. DBs
  db:
    image: postgres:16.1
    container_name: explore-with-me-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d   # пробросить путь на хосте (./initdb): в фиксированную директорию внутри контейнера, которую официальный образ PostgreSQL автоматически обрабатывает при первом запуске
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network
    profiles:
      - default
      - docker

  # 1. Discovery Server (Eureka)
  discovery-server:
    image: discovery-server:latest        # имя образа, который будет создан или использован. Если есть build, образ собирается локально, а не скачивается из Docker Hub. C тегом :latest
    build:
      context: ./infra/discovery-server   # где искать исходники: в пакете ./infra/discovery-server
      dockerfile: Dockerfile              # как собирать образ: используя файл Dockerfile, в этой папке
    ports:
      - "8761:8761"                       # пробросить порт (порт на компьютере (localhost):порт внутри контейнера)
    depends_on:
      db:
        condition: service_healthy
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s                       # проверять каждые 10 секунд
      timeout: 5s                         # ждать ответа не дольше 5 секунд
      retries: 3                          # сделать до 3 попыток, прежде чем считать сервис "нездоровым"
    restart: unless-stopped               # перезапускать, если контейнер не был остановлен вручную
    networks:
      - app-network                       # контейнер должен быть подключен к сети с именем app-network
    profiles:                             # запуск по профилю 'docker compose --profile default up -d'
      - default                           # дефолтный профиль db и discovery остальное запускается на руках (для прямого обращения чз localhost:port - для отладки)
      - docker                            # профиль для запуска в docker

  # 2. Config Server
  config-server:
    image: config-server:latest
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles:
      - docker

  # 3. Event Service
  event-service:
    image: event-service:latest
    deploy:
      restart_policy:
        condition: on-failure             # перезапускать контейнер только если он завершился с ненулевым кодом (упал с ошибкой)
        delay: 5s                         # ждать 5 секунд перед попыткой перезапуска
        max_attempts: 3                   # максимум 3 попытки перезапуска
        window: 120s                      # временное окно, в течение которого считаются попытки. Если за 120 секунд было 3 падения, Docker перестанет пытаться перезапускать контейнер
    build:
      context: ./core/event-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"                       # порт для дебага
    depends_on:
      db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:                          # переменные окружения внутри контейнера
                                          # > - все строки ниже объединить в одну строку с пробелами вместо переносов
                                          # -agentlib:jdwp - настройка удалённой отладки Java (JDWP - Java Debug Wire Protocol).
                                          # Позволяет подключить IDE к работающему контейнеру и ставить breakpoints, как будто
                                          # приложение запущено локально.
                                          # -Duser.timezone - устанавливает часовой пояс по умолчанию для всего приложения
      SPRING_PROFILES_ACTIVE: docker      # пометить, чтобы Spring Boot использовал конфиг 'docker' н.п. event-service-docker.yml
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles:
      - docker

  # 4. User Service
  user-service:
    image: user-service:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: ./core/user-service
      dockerfile: Dockerfile
    ports:
      - "5007:5005"                       # порт для дебага
    depends_on:
      db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles:
      - docker

  # 5. Request Service
  request-service:
    image: request-service:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: ./core/request-service
      dockerfile: Dockerfile
    ports:
      - "5008:5005"                       # порт для дебага
    depends_on:
      db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles:
      - docker

  # 6. Gateway Server
  gateway-server:
    image: gateway-server:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      JAVA_OPTS: >
        -Duser.timezone=Europe/Moscow
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - app-network
    profiles:
      - docker

networks:
  app-network:
    driver: bridge                        # объявляет внутреннюю сеть, чтобы контейнеры могли общяться между собой по имени сервиса (как по hostname) н.п. http://db:5432
