-- liquibase formatted sql

-- changeset smirnovs:001-create-tables
CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    status       VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
--     FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE <- Проверить удаление событий в event-service !!
);

-- Индексы по внешним ключам
CREATE INDEX idx_participation_requests_event_id ON participation_requests (event_id);
CREATE INDEX idx_participation_requests_requester_id ON participation_requests (requester_id);