spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
