/**
 * Протокол передачи данных о сходстве мероприятий
 *
 * События этого типа генерируются в ответ на пользовательские действия:
 * 	- просмотр страницы мероприятия
 *  - заявка на участие в мероприятии
 *  - положительная оценка/лайк мероприятию
 * используется для формирования персонализированных рекомендаций
 */
@namespace("ru.practicum.ewm.stats.avro")
protocol EventSimilarityProtocol {
	/**
     * Значения сходства
     *
     * @param eventA идентификатор мероприятия A
     * @param eventB идентификатор мероприятия B
     * @param score значение рассчитанного сходства мероприятий (от 0.0 до 1.0, где 1.0 - полное совпадение)
     * @param timestamp метка времени, когда было совершено действие, инициировавшее пересчёт
     */
	record EventSimilarityAvro {
		long eventA;
		long eventB;
		double score;
		timestamp_ms timestamp;
	}
}